'''
Provenance entities

.. inheritance-diagram:: entity_management.core
   :top-classes: entity_management.core.Entity
   :parts: 1
'''
from datetime import datetime

from entity_management.mixins import DistributionMixin
from entity_management.base import Identifiable
from entity_management.util import attributes, AttrOf


@attributes({'name': AttrOf(str)})
class Entity(DistributionMixin, Identifiable):
    '''Base class for core Enitities'''
    _type_namespace = 'nsg'
    _url_domain = 'core'

    def __attrs_post_init__(self):
        super(Entity, self).__attrs_post_init__()
        self._type.append('prov:%s' % type(self).__name__)


@attributes({'name': AttrOf(str)})
class Agent(Entity):
    '''Agent

    Args:
        name(str): Name of the agent.
    '''
    pass


@attributes({'version': AttrOf(str)})
class SoftwareAgent(Agent):
    '''Software agent

    Args:
        version(str): Version of the software used.
    '''
    pass


@attributes({
    'used': AttrOf(Identifiable),
    'generated': AttrOf(Identifiable, default=None),
    'startedAtTime': AttrOf(datetime, default=None),
    'wasStartedBy': AttrOf(Agent, default=None),
    })
class Activity(Entity):
    '''Base class for provenance activity.

    Args:
        used(Identifiable): Entity used by this activity.
        generated(Identifiable): Entity generated by this activity.
        startedAtTime(datetime): Activity start time.
        wasStartedBy(Agent): Agent which started the activity.
    '''

    def __attrs_post_init__(self):
        super(Activity, self).__attrs_post_init__()
        if self.startedAtTime is None:
            self._force_attr('startedAtTime', datetime.utcnow())
