'''
Provenance entities

.. inheritance-diagram:: entity_management.prov
   :top-classes: entity_management.prov.Entity
   :parts: 2
'''
from datetime import datetime

from typing import List, Union

from entity_management import sim
from entity_management.simulation import cell
from entity_management.base import Identifiable, QuantitativeValue
from entity_management.util import attributes, AttrOf


@attributes()
class Entity(Identifiable):
    '''Base class for core Enitities'''
    _type_namespace = 'nsg'
    _url_domain = 'core'

    def __attrs_post_init__(self):
        super(Entity, self).__attrs_post_init__()
        self._type.append('prov:%s' % type(self).__name__)


@attributes({'name': AttrOf(str)})
class Agent(Entity):
    '''Agent

    Args:
        name(str): Name of the agent.
    '''
    pass


@attributes({'version': AttrOf(str)})
class SoftwareAgent(Agent):
    '''Software agent

    Args:
        version(str): Version of the software used.
    '''
    pass


@attributes({
    'used': AttrOf(sim.Entity),
    'generated': AttrOf(sim.Entity, default=None),
    'startedAtTime': AttrOf(datetime, default=None),
    'wasStartedBy': AttrOf(Agent, default=None),
    })
class Activity(Entity):
    '''Base class for provenance activity.

    Args:
        used(sim.Entity): Entity used by this activity.
        generated(sim.Entity): Entity generated by this activity.
        startedAtTime(datetime): Activity start time.
        wasStartedBy(Agent): Agent which started the activity.
    '''

    def __attrs_post_init__(self):
        super(Activity, self).__attrs_post_init__()
        if self.startedAtTime is None:
            self._force_attr('startedAtTime', datetime.utcnow())


@attributes({
    'used': AttrOf(cell.Morphology),
    'generated': AttrOf(cell.EModel),
    'wasAssociatedWith': AttrOf(List[Union[Agent, SoftwareAgent]]),
    'bestScore': AttrOf(QuantitativeValue, default=None)
    })
class EModelBuilding(Activity):
    '''EModel building activity.

    Args:
        bestScore(QuantitativeValue): Best score.
        used(cell.Morphology): Morphology which was used to generate the emodel.
        generated(cell.EModel): EModel which was produced.
        wasAssociatedWith(List[Union[Agent, SoftwareAgent]]): Agents associated with
            this activity.
    '''
    _url_domain = 'simulation'
    _url_version = 'v0.1.2'
