'''
Provenance entities

.. inheritance-diagram:: entity_management.prov
   :top-classes: entity_management.prov.Entity
   :parts: 2
'''
from datetime import datetime

from entity_management import sim
from entity_management.base import Identifiable
from entity_management.util import attributes, AttrOf


@attributes()
class Entity(Identifiable):
    '''Base class for core Enitities'''
    _type_namespace = 'nsg'
    _url_domain = 'core'

    def __attrs_post_init__(self):
        super(Entity, self).__attrs_post_init__()
        self._types.append('prov:%s' % type(self).__name__)


@attributes({'name': AttrOf(str)})
class Agent(Entity):
    '''Agent

    Args:
        name(str): Name of the agent.
    '''
    pass


@attributes({
    'used': AttrOf(sim.Entity),
    'generated': AttrOf(sim.Entity, default=None),
    'startedAtTime': AttrOf(datetime, default=None),
    'wasStartedBy': AttrOf(Agent, default=None),
    })
class Activity(Entity):
    '''Base class for provenance activity.

    Args:
        used(sim.Entity): Entity used by this activity.
        generated(sim.Entity): Entity generated by this activity.
        startedAtTime(datetime): Activity start time.
        wasStartedBy(Agent): Agent which started the activity.
    '''

    def __attrs_post_init__(self):
        super(Activity, self).__attrs_post_init__()
        if self.startedAtTime is None:
            self._force_attr('startedAtTime', datetime.utcnow())
