name: tox

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  checks:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-env: ['py3', 'check-packaging', 'lint', 'coverage', 'docs']

    steps:

    - uses: actions/checkout@v4

    - name: Install graphviz if docs tox-env
      if: matrix.tox-env == 'docs'
      run: |
        sudo apt-get update
        sudo apt-get -y install graphviz

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install tox-gh-actions

    - name: Run tox
      run: tox -e ${{ matrix.tox-env }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: BlueBrain/entity-management
